image: golang:latest

stages:
  - build

building:
  stage: build
  script:
    - git clone https://github.com/pepa65/bat
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
  artifacts:
    name: bat
    paths:
     - bat
