image: golang:latest

stages:
  - build

building:
  stage: build
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o batdir ./...
  artifacts:
    name: bat
    paths:
     - bat
