name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sudo apt-get update -y -q
      - run: sudo apt-get install -y golang
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
      - name: "Uploading artifact"
        uses: actions/upload-artifact@v3.1.0
        with:
          path: bat
